name: KotlinPlugin
version: '${project.version}'
main: me.trev.kotlinplugin.KotlinPlugin
api-version: 1.19
authors: [ trev ]
description: plugin written in kotlin
commands:
  pig:
    description: makes pigs go towards players and explode when they are near
    usage: /<command>
  target:
    description: set/get what entity pigs targets
    usage: /<command> [get|set]
  speed:
    description: set/get the speed of pig
    usage: /<command> [get|set]