name: KotlinPlugin
version: '${project.version}'
main: me.trev.kotlinplugin.KotlinPlugin
api-version: 1.19
authors: [ trev ]
description: plugin written in kotlin
commands:
  pig:
    description: makes pigs go towards players and explode when they are near
    usage: /<command>
  settarget:
    description: set what entity pigs targets
    usage: /<command> entity
  gettarget:
    description: get what entity pigs targets
    usage: /<command>